#ifndef ROADNETWORKGRAPH_DEFINES_H
#define ROADNETWORKGRAPH_DEFINES_H

#define MAX_VERTEX_IN_CONNECTIONS 10
#define MAX_VERTEX_OUT_CONNECTIONS 10
// MAX_VERTEX_ADJACENCIES = MAX_VERTEX_IN_CONNECTIONS + MAX_VERTEX_OUT_CONNECTIONS
#define MAX_VERTEX_ADJACENCIES 20
#define MAX_EDGES_PER_QUADRANT 1000
#define MAX_VERTICES_PER_PRIMITIVE 100

namespace RoadNetworkGraph
{

typedef int VertexIndex;
typedef int EdgeIndex;
typedef int QuadrantIndex;
typedef int QuadrantEdgesIndex;

}

#endif