#ifndef ROADNETWORKGRAPH_DEFINES_H
#define ROADNETWORKGRAPH_DEFINES_H

#define MAX_VERTEX_IN_CONNECTIONS 100
#define MAX_VERTEX_OUT_CONNECTIONS 4
// MAX_VERTEX_ADJACENCIES = MAX_VERTEX_IN_CONNECTIONS + MAX_VERTEX_OUT_CONNECTIONS
#define MAX_VERTEX_ADJACENCIES 104
#define MAX_EDGES_PER_QUADRANT 50000
#define MAX_VERTICES_PER_PRIMITIVE 1000

namespace RoadNetworkGraph
{

typedef int VertexIndex;
typedef int EdgeIndex;
typedef int QuadrantIndex;
typedef int QuadrantEdgesIndex;

}

#endif