#ifndef INTERSECTIONTYPE_H
#define INTERSECTIONTYPE_H

enum IntersectionType
{
	NONE,
	SOURCE_SOURCE_SNAPPING,
	SOURCE_DESTINATION_SNAPPING,
	DESTINATION_SOURCE_SNAPPING,
	DESTINATION_DESTINATION_SNAPPING,
	EDGE_INTERSECTION

};

#endif